name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Ironbark? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Ironbark does this relate to?
      options:
        - Agent (TUI/CLI)
        - Admin Console
        - Desktop App
        - VS Code Extension
        - SDK / Plugin
        - New Component
        - Other
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and feature requests to avoid duplicates
          required: true
